version: '3.1'

services:
  nestjs:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./server:/home/node/app


  mongo:
    image: bitnami/mongodb:5.0.17
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: 123456
      MONGODB_DATABASE: mongo

volumes:
  mongodb_data:
    driver: local